name: Deploy

on:
  push:
    branches:
      - api-routes
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ecr:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ecr_repo_name: ${{ vars.aws_account_id }}-weighted-target-ecs
    outputs:
      ecr_repo_name: ${{ steps.set-envs.outputs.ECR_REPO_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.aws_region }}
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/ecr
          terraform init
    
      - name: Deploy
        shell: bash
        id: deploy
        run: |
          cd tf/ecr
          terraform apply -auto-approve -var-file=${{ github.workspace }}/variables.tfvars

      - name: Set env vars
        id: set-envs
        shell: bash
        run: |
          cd tf/ecr
          ECR_REPO_NAME=$(terraform output -raw ecr_repo_name)
          echo "ECR_REPO_NAME=$ECR_REPO_NAME" >> $GITHUB_OUTPUT

  image:
    runs-on: ubuntu-latest
    needs: ecr
    outputs:
      image_uri: ${{ steps.set-image-uri.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.aws_region }}
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.aws_role }}
          role-session-name: GitHubActions

      - name: Build and push detected changes
        id: build-image
        uses: ./.github/actions/build_image
        with:
          aws_account_id: ${{ vars.aws_account_id }}
          aws_region: ${{ vars.aws_region }}
          ecr_repository_name: ${{ needs.ecr.outputs.ecr_repo_name }}

      - name: Set image_uri output
        id: set-image-uri
        run: |
          echo "image_uri=${{ env.IMAGE_URI }}" >> $GITHUB_OUTPUT

  network:
    runs-on: ubuntu-latest
    outputs:
      lb_security_group_id: ${{ steps.set-envs.outputs.LB_SECURITY_GROUP_ID }}
      lb_ecs_target_group_arn: ${{ steps.set-envs.outputs.LB_ECS_TARGET_GROUP_ARN }}
      lb_lambda_target_group_arn: ${{ steps.set-envs.outputs.LB_LAMBDA_TARGET_GROUP_ARN }}
      api_invoke_url: ${{ steps.set-envs.outputs.API_INVOKE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.aws_region }}
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/network
          terraform init
    
      - name: Deploy
        shell: bash
        id: deploy
        run: |
          cd tf/network
          terraform apply -auto-approve -var-file=${{ github.workspace }}/variables.tfvars

      - name: Set env vars
        id: set-envs
        shell: bash
        run: |
          cd tf/network
          LB_SECURITY_GROUP_ID=$(terraform output -raw lb_security_group_id)
          API_INVOKE_URL=$(terraform output -raw api_invoke_url)
          LB_ECS_TARGET_GROUP_ARN=$(terraform output -raw lb_ecs_target_group_arn)
          LB_LAMBDA_TARGET_GROUP_ARN=$(terraform output -raw lb_lambda_target_group_arn)
          echo "LB_SECURITY_GROUP_ID=$LB_SECURITY_GROUP_ID" >> $GITHUB_OUTPUT
          echo "API_INVOKE_URL=$API_INVOKE_URL" >> $GITHUB_OUTPUT
          echo "LB_ECS_TARGET_GROUP_ARN=$LB_ECS_TARGET_GROUP_ARN" >> $GITHUB_OUTPUT
          echo "LB_LAMBDA_TARGET_GROUP_ARN=$LB_LAMBDA_TARGET_GROUP_ARN" >> $GITHUB_OUTPUT

  ecs:
    needs:
      - ecr
      - image
      - network
    runs-on: ubuntu-latest
    env:
      TF_VAR_ecr_repo_name: ${{ needs.ecr.outputs.ecr_repo_name }}
      TF_VAR_ecs_image_uri: ${{ needs.image.outputs.image_uri }}
      TF_VAR_lb_security_group_id: ${{ needs.network.outputs.lb_security_group_id }}
      TF_VAR_lb_target_group_arn: ${{ needs.network.outputs.lb_ecs_target_group_arn}}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.aws_region }}
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/ecs
          terraform init
    
      - name: Deploy
        shell: bash
        id: deploy
        run: |
          cd tf/ecs
          terraform apply -auto-approve -var-file=${{ github.workspace }}/variables.tfvars

  lambda:
    needs: network
    runs-on: ubuntu-latest
    env:
      TF_VAR_lambda_zip_path: ${{ github.ref_name }}.zip
      TF_VAR_lb_security_group_id: ${{ needs.network.outputs.lb_security_group_id }}
      TF_VAR_lb_target_group_arn: ${{ needs.network.outputs.lb_lambda_target_group_arn}}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.aws_region }}
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.aws_role }}
          role-session-name: GitHubActions

      - name: Build
        shell: bash
        run: |
            cd src
            npm install

      - name: zip
        shell: bash
        run: |
            cd src
            zip -r ${{ env.TF_VAR_lambda_zip_path }} *

      - name: Init
        shell: bash
        run: |
          cd tf/lambda
          terraform init
        
      - name: Deploy
        shell: bash
        id: deploy
        run: |
          cd tf/lambda
          terraform apply -auto-approve -var-file=${{ github.workspace }}/variables.tfvars
